### ISSUE TITLE
Multiple comments combined together for single client login

### ISSUE THREAD

**Issue by arpan-sur** [vmware/workflowTools#3]
using the API we are noticing an issue with adding comments. We see that multiple comments are being combined into a single comment and updated into the ticket when using the same login

Reproduction steps:
1. Create a bugzilla object(client)
2. login using username and password
2. Call client.addBugComment(Bug number, comment) multiple times

Output:
some comments are combined and posted as a single comment. 

``

**Comment by damienbiggs** [comment]
Code is using bugzilla api for each comment.
